### ISSUE TITLE
FeatureRequest: Export DeadJobs

### ISSUE THREAD

**Issue by alexanderkraemer** [ThomasKoppensteiner/sidekiq-undertaker#51]
Exporting dead jobs into a csv/json file for later use might be a awesome feature! Let me know what you think about it!

**Comment by ThomasKoppensteiner** [comment]
Based on the Undertaker filter or for all dead jobs?

**Comment by ThomasKoppensteiner** [comment]
@ldellisola is working on this.

**Comment by ThomasKoppensteiner** [comment]
Done within #60 and released as version `1.3.0`.
